In [22]:
#Brian Domingo
#100528062
import numpy as np
import matplotlib.pyplot as plt
import random as rnd

def beforeWhiteWash(n):
    a = np.arange(n*3.).reshape(n, 3)
    
    for x in range(0, n):
        for y in range (0, 3):
            a[x][y] = rnd.random()
            
    return(a)

def WhiteWash(a):
    for x in range(0, n):
        for y in range (0, 3):
            a[x][y] = (a[x][y]+1) / 2
    print ("After White Wash")
    print (a)
    plt.imshow(a)
    plt.show()

n = 5
print("Before White Wash")
a = beforeWhiteWash(n)
print (a)
print ("")

WhiteWash(a)

    

Before White Wash
[[ 0.51014338  0.4627435   0.70435094]
 [ 0.02032718  0.78490962  0.14739537]
 [ 0.71664272  0.33155409  0.72213337]
 [ 0.79184282  0.60797248  0.8718671 ]
 [ 0.57396624  0.42240846  0.97144347]]

After White Wash
[[ 0.75507169  0.73137175  0.85217547]
 [ 0.51016359  0.89245481  0.57369768]
 [ 0.85832136  0.66577705  0.86106668]
 [ 0.89592141  0.80398624  0.93593355]
 [ 0.78698312  0.71120423  0.98572174]]
